# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build for MyCandidate App

on:
  push:
    branches:
    - prod

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Get Environment Variables and Create Configuration File
    #   uses: alekangelov/secret-envfile@v1
    #   with:
    #     content: ${{ secrets.ENV_PROD }}
    #     filename: main/config/production.cfg

    - name: Create ini File for Alembic
      uses: alekangelov/secret-envfile@v1
      with:
        content: ${{ secrets.INI_PROD }}
        filename: alembic.ini

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Database Migrations
      run: |
        alembic upgrade head
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
        
    # - name: Test with pytest
    #   run: |
    #     pytest

    # - name: Seed data to DB
    #   run: |
    #     python rebuild_db.py
    #   env:
    #     DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}